version: '2.2'
services:
  rally:
    image: openfda_rally
    container_name: rally
    # pick one command
    # command: esrally list tracks
    #
    # command: esrally race --track=companies --pipeline=benchmark-only --target-hosts=es01:9200 --challenge=unscored-challenge --track-repository=camden_demo --offline
    # command: esrally race --track=companies --pipeline=benchmark-only --target-hosts=es01:9200 --challenge=scored-challenge --track-repository=camden_demo --offline
    #
    command: esrally race --track=foodevent --pipeline=benchmark-only --target-hosts=es01:9200 --challenge=query-gender --track-repository=openfda_testing --offline
    #command: esrally race --track=foodevent --pipeline=benchmark-only --target-hosts=es01:9200 --challenge=query-age --track-repository=openfda_testing --offline
    #command: esrally race --track=foodevent --pipeline=benchmark-only --target-hosts=es01:9200 --challenge=query-both --track-repository=openfda_testing --offline
    volumes:
      - rally:/rally/.rally
    networks:
      - esnet
    depends_on:
      es01:
        condition: service_healthy
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.1
    container_name: es01
    environment:
      # Form a single-node Elasticsearch cluster.  Reference:
      # https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-discovery-settings.html
      - discovery.type=single-node
      # Disable Elasticsearch security features on the node.  Reference:
      # https://www.elastic.co/guide/en/elasticsearch/reference/current/security-settings.html
      - xpack.security.enabled=false
      # Set Elasticsearch's JVM heap size.  Reference:
      # https://www.elastic.co/guide/en/elasticsearch/reference/current/advanced-configuration.html
      # - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 19200:9200
    networks:
      - esnet
    healthcheck:
          test: curl -f http://localhost:9200
          interval: 5s
          timeout: 2s
          retries: 10
networks:
  esnet:
    name: rally-tests

volumes:
  esdata1:
    driver: local
    name: openfda_esdata
  rally:
    driver: local
    name: rally_data
