version: '3'

services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.1
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    networks:
      - openfdanet
    ports:
      - "9200"
  api:
    build: ./api/faers
    environment:
      - ES_HOST=es:9200
    depends_on:
      - es
    #volumes:
    #  - apidata1:/rally/.rally
    networks:
      - openfdanet
    ports:
      - 8000:8000
  pipeline:
    build: .
    environment:
      - ES_HOST=es:9200
    depends_on:
      - es
    #volumes:
    #  - pipelinedata1:/rally/.rally
    networks:
      - openfdanet
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535

networks:
  openfdanet:
    name: openfda-test-net

volumes:
  esdata1:
    driver: local
    name: openfda_esdata
  #apidata1:
  #  driver: local
  #pipelinedata1:
  #  driver: local